name: CI
on: 
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "22.x"
      - uses: subosito/flutter-action@v1
        with:
          chanel: "stable"
      - run: flutter pub get
      - run:  flutter analyze
      - run: flutter test